# Generated by Django 2.2 on 2020-10-26 16:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transaccion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ExpensesUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=80, unique=True)),
                ('presupuesto', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('universidad', models.CharField(max_length=80)),
                ('carrera', models.CharField(max_length=120)),
                ('semestre', models.IntegerField(validators=[django.core.validators.MaxValueValidator(20)])),
                ('feed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transaccion.Transaccion')),
            ],
        ),
    ]
