# Generated by Django 2.1.5 on 2020-10-26 04:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transaccion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='XpensesUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=80, unique=True)),
                ('presupuesto', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('universidad', models.CharField(max_length=80)),
                ('carrera', models.CharField(max_length=120)),
                ('semestre', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(20)])),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaccion.Transaccion')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
