# Generated by Django 2.2 on 2020-10-26 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expensesuser',
            name='feed',
        ),
    ]
