# Generated by Django 2.1.5 on 2020-10-26 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0002_auto_20201026_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xpensesuser',
            name='feed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transaccion.Transaccion'),
        ),
    ]
